title: [CharleStephen's Github Page]
description: [Thanks for dropping by.]

theme: jekyll-theme-modernist
plugins:
  - jekyll-analytics
  - jekyll-sitemap
  - jekyll-seo-tag
jekyll_analytics:
GoogleAnalytics:
  id: UA-158763117-1
  anonymizeIp: false
url: "https://git.cst.nyc"
markdown: kramdown
show_downloads: "true"
google_analytics: UA-158763117-1
github:
  zip_url: http://github.com/download.zip
  another_url: https://git.cst.nyc/download.zip
plugins:
  - "jekyll-github-metadata"
repository: charlestephen/charlestephen.github.io
github: [metadata]
increment: true
watch: true
